Makefile: Fix a bug related to linker ld
When we built the code on ubuntu 16.04, we got the error:
  | main.c:(.text+0x63f): undefined reference to sqrt
  | collect2: error: ld returned 1 exit status
  | makefile:10: recipe for target main failed
We need to arrange the GCC arguments, so change a little in Makefile.

Signed-off-by: Hoang Van Tuyen <tuyen.hv.3i@gmail.com>